### ISSUE TITLE
Test/document alternative "in-process only approach"

### ISSUE THREAD

**Issue by Doctor-love** [menacit/k8s_crlish_authorizer#13]
When utilizing the ["structured authorization configuration" feature](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#using-configuration-file-for-authorization), administrators can configure "match conditions" using CEL expressions to determine if an authorizer should be called based on properties of the request (path, group memberships, authenticator extra properties, etc!).

Perhaps we could combine this feature with usage of the "AlwaysDeny" authorizer - configure match conditions that checks if the request contains deny listed credential IDs and, if so, calls the "AlwaysDeny" authorizer?

While a bit of a hack, the benefit is that the evaluation will be performed "in-process" on the API server and remove the need for external webhooks - less complexity, fewer things that can break.

This alternative approach to perform revocation checking should be tested and documented.

**Comment by Doctor-love** [comment]
This won't work at the moment as only webhook authorizers seem to support match conditions.
If it would, the crlish could be replaced by a configuration like:

```yaml
---
apiVersion: apiserver.config.k8s.io/v1
kind: AuthorizationConfiguration
authorizers:
  - type: AlwaysDeny
    name: crlish
    alwaysdeny:
      matchConditions:
        - expression: "'authentication.kubernetes.io/credential-id' in request.extra"
        - expression: >-
            request.extra["authentication.kubernetes.io/credential-id"].exists_one(
                id,
                id == "JTI=1234" ||
                id == "JTI=5678" ||
                id == "X509SHA256=474d[...]0c91"
            )
  - type: Node
    name: node
  - type: RBAC
    name: rbac
```
